[build.environment]
  NODE_VERSION = "16"

[build]
  publish = "dist"
  command = "pnpm build"

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-playwright-cache"
